Fix bugs input/output functions for tdigest
For text format, the input function was not updated to consider the
"flags" field, resulting in trivial failures. It also used %s to parse
centroids, which however matches only non-whitespace characters, so
only the first centroid was matched. Fixed by properly parsing the
"flags" field and using %n instead.

The receive function was broken too, thanks to using pq_getmsgint with
sizeof(int64). That is unsupported, and results with

  ERROR: unsupported integer size 8

Fix by using pq_getmsgint64 instead.

This also includes regression tests testing the text conversion.